all:
	gcc -Wall -pedantic -ansi -g -Iinclude   -c -o lab9.o src/main.c
	gcc -Wall -pedantic -ansi -g -Iinclude   -c -o restaurant.o src/structInfo.c
	gcc -Llib  lab9.o restaurant.o  -lbintree -o lab9runnable


